/*
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl.ui;

import com.google.inject.Injector;
import de.htwdd.sf.beleg.s87622.s87673.ui.internal.S87673Activator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class MyDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(S87673Activator.class);
	}
	
	@Override
	protected Injector getInjector() {
		S87673Activator activator = S87673Activator.getInstance();
		return activator != null ? activator.getInjector(S87673Activator.ORG_XTEXT_EXAMPLE_MYDSL_MYDSL) : null;
	}

}
