/*
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl.ui.labeling;

import com.google.inject.Inject;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;
/**
 * Provides labels for EObjects.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#label-provider
 */
public class MyDslLabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	public MyDslLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}
 
	// Labels and icons can be computed like this:
	String text(User_Story ele) {
		return "User Story : " + ele.getTitle().getSubstantiv() + " " + ele.getTitle().getInfinitiv().getWord();
	}
 
	String text(Title ele) {
		return "Title : " + ele.getSubstantiv() + " " + ele.getInfinitiv().getWord();
	}
	String text(Rolle ele) {
		return "Rolle : " + ele.getSubstantiv();
	}
	String text(Nutzen ele) {
		return "Nutzen : " + ele.getSubject() + " "+ ele.getVerb();
	}
	String text(Ziel_Wunsch ele) {
		return "Ziel und Wunsch : " + ele.getSubject() + " "+ ele.getInfinitiv().getWord();
	}

}
