/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rolle</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Rolle#getSubstantiv <em>Substantiv</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRolle()
 * @model
 * @generated
 */
public interface Rolle extends EObject
{
  /**
   * Returns the value of the '<em><b>Substantiv</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Substantiv</em>' attribute.
   * @see #setSubstantiv(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRolle_Substantiv()
   * @model
   * @generated
   */
  String getSubstantiv();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Rolle#getSubstantiv <em>Substantiv</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Substantiv</em>' attribute.
   * @see #getSubstantiv()
   * @generated
   */
  void setSubstantiv(String value);

} // Rolle
