/**
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ziel Wunsch</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Ziel_Wunsch#getSubject <em>Subject</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Ziel_Wunsch#getInfinitiv <em>Infinitiv</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getZiel_Wunsch()
 * @model
 * @generated
 */
public interface Ziel_Wunsch extends EObject
{
  /**
   * Returns the value of the '<em><b>Subject</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Subject</em>' attribute.
   * @see #setSubject(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getZiel_Wunsch_Subject()
   * @model
   * @generated
   */
  String getSubject();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Ziel_Wunsch#getSubject <em>Subject</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Subject</em>' attribute.
   * @see #getSubject()
   * @generated
   */
  void setSubject(String value);

  /**
   * Returns the value of the '<em><b>Infinitiv</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Infinitiv</em>' containment reference.
   * @see #setInfinitiv(Infinitiv)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getZiel_Wunsch_Infinitiv()
   * @model containment="true"
   * @generated
   */
  Infinitiv getInfinitiv();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Ziel_Wunsch#getInfinitiv <em>Infinitiv</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Infinitiv</em>' containment reference.
   * @see #getInfinitiv()
   * @generated
   */
  void setInfinitiv(Infinitiv value);

} // Ziel_Wunsch
