/*
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class MyDslGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class User_StoriesElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.User_Stories");
		private final Assignment cUser_storyAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cUser_storyUser_StoryParserRuleCall_0 = (RuleCall)cUser_storyAssignment.eContents().get(0);
		
		//User_Stories:
		//    user_story+=User_Story+;
		@Override public ParserRule getRule() { return rule; }
		
		//user_story+=User_Story+
		public Assignment getUser_storyAssignment() { return cUser_storyAssignment; }
		
		//User_Story
		public RuleCall getUser_storyUser_StoryParserRuleCall_0() { return cUser_storyUser_StoryParserRuleCall_0; }
	}
	public class User_StoryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.User_Story");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cTitleAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cTitleTitleParserRuleCall_0_0 = (RuleCall)cTitleAssignment_0.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cUmKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cNutzenAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cNutzenNutzenParserRuleCall_3_0 = (RuleCall)cNutzenAssignment_3.eContents().get(0);
		private final Keyword cMöchteIchAlsKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cRolleAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cRolleRolleParserRuleCall_5_0 = (RuleCall)cRolleAssignment_5.eContents().get(0);
		private final Assignment cZiel_wunschAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cZiel_wunschZiel_WunschParserRuleCall_6_0 = (RuleCall)cZiel_wunschAssignment_6.eContents().get(0);
		private final Keyword cFullStopKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//User_Story:
		//    title=Title ":" 'Um' nutzen=Nutzen ', möchte ich als' rolle=Rolle ziel_wunsch=Ziel_Wunsch '.';
		@Override public ParserRule getRule() { return rule; }
		
		//title=Title ":" 'Um' nutzen=Nutzen ', möchte ich als' rolle=Rolle ziel_wunsch=Ziel_Wunsch '.'
		public Group getGroup() { return cGroup; }
		
		//title=Title
		public Assignment getTitleAssignment_0() { return cTitleAssignment_0; }
		
		//Title
		public RuleCall getTitleTitleParserRuleCall_0_0() { return cTitleTitleParserRuleCall_0_0; }
		
		//":"
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }
		
		//'Um'
		public Keyword getUmKeyword_2() { return cUmKeyword_2; }
		
		//nutzen=Nutzen
		public Assignment getNutzenAssignment_3() { return cNutzenAssignment_3; }
		
		//Nutzen
		public RuleCall getNutzenNutzenParserRuleCall_3_0() { return cNutzenNutzenParserRuleCall_3_0; }
		
		//', möchte ich als'
		public Keyword getMöchteIchAlsKeyword_4() { return cMöchteIchAlsKeyword_4; }
		
		//rolle=Rolle
		public Assignment getRolleAssignment_5() { return cRolleAssignment_5; }
		
		//Rolle
		public RuleCall getRolleRolleParserRuleCall_5_0() { return cRolleRolleParserRuleCall_5_0; }
		
		//ziel_wunsch=Ziel_Wunsch
		public Assignment getZiel_wunschAssignment_6() { return cZiel_wunschAssignment_6; }
		
		//Ziel_Wunsch
		public RuleCall getZiel_wunschZiel_WunschParserRuleCall_6_0() { return cZiel_wunschZiel_WunschParserRuleCall_6_0; }
		
		//'.'
		public Keyword getFullStopKeyword_7() { return cFullStopKeyword_7; }
	}
	public class TitleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Title");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cSubstantivAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cSubstantivUPPERCASE_WORDTerminalRuleCall_0_0 = (RuleCall)cSubstantivAssignment_0.eContents().get(0);
		private final Assignment cInfinitivAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cInfinitivInfinitivParserRuleCall_1_0 = (RuleCall)cInfinitivAssignment_1.eContents().get(0);
		
		//Title:
		//    substantiv=UPPERCASE_WORD infinitiv=Infinitiv;
		@Override public ParserRule getRule() { return rule; }
		
		//substantiv=UPPERCASE_WORD infinitiv=Infinitiv
		public Group getGroup() { return cGroup; }
		
		//substantiv=UPPERCASE_WORD
		public Assignment getSubstantivAssignment_0() { return cSubstantivAssignment_0; }
		
		//UPPERCASE_WORD
		public RuleCall getSubstantivUPPERCASE_WORDTerminalRuleCall_0_0() { return cSubstantivUPPERCASE_WORDTerminalRuleCall_0_0; }
		
		//infinitiv=Infinitiv
		public Assignment getInfinitivAssignment_1() { return cInfinitivAssignment_1; }
		
		//Infinitiv
		public RuleCall getInfinitivInfinitivParserRuleCall_1_0() { return cInfinitivInfinitivParserRuleCall_1_0; }
	}
	public class NutzenElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Nutzen");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cSubjectAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cSubjectUPPERCASE_WORDTerminalRuleCall_0_0 = (RuleCall)cSubjectAssignment_0.eContents().get(0);
		private final Assignment cVerbAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cVerbLOWERCASE_WORDTerminalRuleCall_1_0 = (RuleCall)cVerbAssignment_1.eContents().get(0);
		
		//Nutzen:
		//    subject=UPPERCASE_WORD verb=LOWERCASE_WORD;
		@Override public ParserRule getRule() { return rule; }
		
		//subject=UPPERCASE_WORD verb=LOWERCASE_WORD
		public Group getGroup() { return cGroup; }
		
		//subject=UPPERCASE_WORD
		public Assignment getSubjectAssignment_0() { return cSubjectAssignment_0; }
		
		//UPPERCASE_WORD
		public RuleCall getSubjectUPPERCASE_WORDTerminalRuleCall_0_0() { return cSubjectUPPERCASE_WORDTerminalRuleCall_0_0; }
		
		//verb=LOWERCASE_WORD
		public Assignment getVerbAssignment_1() { return cVerbAssignment_1; }
		
		//LOWERCASE_WORD
		public RuleCall getVerbLOWERCASE_WORDTerminalRuleCall_1_0() { return cVerbLOWERCASE_WORDTerminalRuleCall_1_0; }
	}
	public class RolleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Rolle");
		private final Assignment cSubstantivAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cSubstantivUPPERCASE_WORDTerminalRuleCall_0 = (RuleCall)cSubstantivAssignment.eContents().get(0);
		
		//Rolle:
		//    substantiv=UPPERCASE_WORD;
		@Override public ParserRule getRule() { return rule; }
		
		//substantiv=UPPERCASE_WORD
		public Assignment getSubstantivAssignment() { return cSubstantivAssignment; }
		
		//UPPERCASE_WORD
		public RuleCall getSubstantivUPPERCASE_WORDTerminalRuleCall_0() { return cSubstantivUPPERCASE_WORDTerminalRuleCall_0; }
	}
	public class Ziel_WunschElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Ziel_Wunsch");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cSubjectAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cSubjectUPPERCASE_WORDTerminalRuleCall_0_0 = (RuleCall)cSubjectAssignment_0.eContents().get(0);
		private final Assignment cInfinitivAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cInfinitivInfinitivParserRuleCall_1_0 = (RuleCall)cInfinitivAssignment_1.eContents().get(0);
		
		//Ziel_Wunsch:
		//    subject=UPPERCASE_WORD infinitiv=Infinitiv;
		@Override public ParserRule getRule() { return rule; }
		
		//subject=UPPERCASE_WORD infinitiv=Infinitiv
		public Group getGroup() { return cGroup; }
		
		//subject=UPPERCASE_WORD
		public Assignment getSubjectAssignment_0() { return cSubjectAssignment_0; }
		
		//UPPERCASE_WORD
		public RuleCall getSubjectUPPERCASE_WORDTerminalRuleCall_0_0() { return cSubjectUPPERCASE_WORDTerminalRuleCall_0_0; }
		
		//infinitiv=Infinitiv
		public Assignment getInfinitivAssignment_1() { return cInfinitivAssignment_1; }
		
		//Infinitiv
		public RuleCall getInfinitivInfinitivParserRuleCall_1_0() { return cInfinitivInfinitivParserRuleCall_1_0; }
	}
	public class InfinitivElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Infinitiv");
		private final Assignment cWordAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cWordLOWERCASE_WORDTerminalRuleCall_0 = (RuleCall)cWordAssignment.eContents().get(0);
		
		//Infinitiv:
		//    word=LOWERCASE_WORD;
		@Override public ParserRule getRule() { return rule; }
		
		//word=LOWERCASE_WORD
		public Assignment getWordAssignment() { return cWordAssignment; }
		
		//LOWERCASE_WORD
		public RuleCall getWordLOWERCASE_WORDTerminalRuleCall_0() { return cWordLOWERCASE_WORDTerminalRuleCall_0; }
	}
	
	
	private final User_StoriesElements pUser_Stories;
	private final User_StoryElements pUser_Story;
	private final TitleElements pTitle;
	private final NutzenElements pNutzen;
	private final RolleElements pRolle;
	private final Ziel_WunschElements pZiel_Wunsch;
	private final InfinitivElements pInfinitiv;
	private final TerminalRule tUPPERCASE_WORD;
	private final TerminalRule tLOWERCASE_WORD;
	private final TerminalRule tUPERCASE_LETTER;
	private final TerminalRule tLOWERCASE_LETTER;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MyDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pUser_Stories = new User_StoriesElements();
		this.pUser_Story = new User_StoryElements();
		this.pTitle = new TitleElements();
		this.pNutzen = new NutzenElements();
		this.pRolle = new RolleElements();
		this.pZiel_Wunsch = new Ziel_WunschElements();
		this.pInfinitiv = new InfinitivElements();
		this.tUPPERCASE_WORD = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.UPPERCASE_WORD");
		this.tLOWERCASE_WORD = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.LOWERCASE_WORD");
		this.tUPERCASE_LETTER = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.UPERCASE_LETTER");
		this.tLOWERCASE_LETTER = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.LOWERCASE_LETTER");
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.mydsl.MyDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//User_Stories:
	//    user_story+=User_Story+;
	public User_StoriesElements getUser_StoriesAccess() {
		return pUser_Stories;
	}
	
	public ParserRule getUser_StoriesRule() {
		return getUser_StoriesAccess().getRule();
	}
	
	//User_Story:
	//    title=Title ":" 'Um' nutzen=Nutzen ', möchte ich als' rolle=Rolle ziel_wunsch=Ziel_Wunsch '.';
	public User_StoryElements getUser_StoryAccess() {
		return pUser_Story;
	}
	
	public ParserRule getUser_StoryRule() {
		return getUser_StoryAccess().getRule();
	}
	
	//Title:
	//    substantiv=UPPERCASE_WORD infinitiv=Infinitiv;
	public TitleElements getTitleAccess() {
		return pTitle;
	}
	
	public ParserRule getTitleRule() {
		return getTitleAccess().getRule();
	}
	
	//Nutzen:
	//    subject=UPPERCASE_WORD verb=LOWERCASE_WORD;
	public NutzenElements getNutzenAccess() {
		return pNutzen;
	}
	
	public ParserRule getNutzenRule() {
		return getNutzenAccess().getRule();
	}
	
	//Rolle:
	//    substantiv=UPPERCASE_WORD;
	public RolleElements getRolleAccess() {
		return pRolle;
	}
	
	public ParserRule getRolleRule() {
		return getRolleAccess().getRule();
	}
	
	//Ziel_Wunsch:
	//    subject=UPPERCASE_WORD infinitiv=Infinitiv;
	public Ziel_WunschElements getZiel_WunschAccess() {
		return pZiel_Wunsch;
	}
	
	public ParserRule getZiel_WunschRule() {
		return getZiel_WunschAccess().getRule();
	}
	
	//Infinitiv:
	//    word=LOWERCASE_WORD;
	public InfinitivElements getInfinitivAccess() {
		return pInfinitiv;
	}
	
	public ParserRule getInfinitivRule() {
		return getInfinitivAccess().getRule();
	}
	
	//terminal UPPERCASE_WORD:
	//    UPERCASE_LETTER LOWERCASE_LETTER+;
	public TerminalRule getUPPERCASE_WORDRule() {
		return tUPPERCASE_WORD;
	}
	
	//terminal LOWERCASE_WORD:
	//    LOWERCASE_LETTER+;
	public TerminalRule getLOWERCASE_WORDRule() {
		return tLOWERCASE_WORD;
	}
	
	//terminal fragment UPERCASE_LETTER:
	//    ('A'..'Z') | 'Ä' | 'Ü' | 'Ö';
	public TerminalRule getUPERCASE_LETTERRule() {
		return tUPERCASE_LETTER;
	}
	
	//terminal fragment LOWERCASE_LETTER:
	//    ('a'..'z') | 'ä' | 'ü' | 'ö' | 'ß';
	public TerminalRule getLOWERCASE_LETTERRule() {
		return tLOWERCASE_LETTER;
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
